"use client";
import { useState } from "react";
type Finding={label:string;confidence?:number;location?:Record<string,number>};
export default function ClinicalAIResults({analysis}:{analysis:any}){
 const findings:Finding[]=safe(analysis.findings), limitations:string[]=safe(analysis.limitations);
 const [text,setText]=useState(""); const [msg,setMsg]=useState("");
 async function add(){if(!text.trim())return;setMsg("Saving…");const r=await fetch(`/api/analyses/${analysis.id}/annotations`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({text})});const j=await r.json();if(!r.ok){setMsg(j.error||"Failed");return;}setText("");setMsg("Annotation saved.");window.location.reload();}
 return <section className="space-y-6">
  <div className="card"><div className="flex items-center justify-between"><h2 className="text-lg font-semibold">Structured AI findings</h2><span className="rounded-full border px-2 py-1 text-xs">{analysis.status}</span></div>
   {findings.length?<div className="mt-4 space-y-3">{findings.map((f,i)=><div key={i} className="rounded-lg border p-3"><div className="flex justify-between gap-4"><span className="font-medium">{f.label}</span>{typeof f.confidence==='number'&&<span className="text-sm">{(f.confidence*100).toFixed(1)}% confidence</span>}</div>{f.location&&<p className="mt-1 text-xs text-slate-500">Location metadata: {JSON.stringify(f.location)}</p>}</div>)}</div>:<p className="mt-4 text-sm text-slate-500">No structured findings are available from the model.</p>}
  </div>
  <div className="card"><h2 className="text-lg font-semibold">Limitations & safety context</h2>{limitations.length?<ul className="mt-3 list-disc space-y-1 pl-5 text-sm">{limitations.map((x,i)=><li key={i}>{x}</li>)}</ul>:<p className="mt-3 text-sm text-slate-500">No limitations supplied by the model.</p>}<p className="mt-4 rounded-lg bg-amber-50 p-3 text-sm text-amber-900">AI output is decision-support information. It is not independently presented as a diagnosis and requires qualified clinician review.</p></div>
  <div className="card"><h2 className="text-lg font-semibold">Model provenance</h2><dl className="mt-3 grid grid-cols-2 gap-3 text-sm"><dt className="text-slate-500">Model</dt><dd>{analysis.modelName}</dd><dt className="text-slate-500">Version</dt><dd>{analysis.modelVersion}</dd><dt className="text-slate-500">Inference runs</dt><dd>{analysis.inferenceRuns?.length??0}</dd>{analysis.inferenceRuns?.[0]&&<><dt className="text-slate-500">Latest request hash</dt><dd className="break-all font-mono text-xs">{analysis.inferenceRuns[0].requestHash}</dd><dt className="text-slate-500">Latest status</dt><dd>{analysis.inferenceRuns[0].status}</dd></>}</dl></div>
  <div className="card"><h2 className="text-lg font-semibold">Clinician annotations</h2><div className="mt-3 space-y-3">{analysis.annotations?.length?analysis.annotations.map((a:any)=><div key={a.id} className="rounded-lg border p-3"><p>{a.text}</p><p className="mt-1 text-xs text-slate-500">{a.author?.name??"Clinician"} · {new Date(a.createdAt).toLocaleString()}</p></div>):<p className="text-sm text-slate-500">No annotations recorded.</p>}</div><textarea value={text} onChange={e=>setText(e.target.value)} className="mt-4 min-h-24 w-full rounded-lg border p-3" placeholder="Add a clinician annotation"/><button onClick={add} className="btn mt-2 bg-slate-900 text-white">Add annotation</button>{msg&&<p className="mt-2 text-xs text-slate-500">{msg}</p>}</div>
 </section>;
}
function safe(v:any){if(!v)return [];try{return JSON.parse(v)}catch{return []}}
